#!/usr/bin/env bash
# Portable commit-message policy check.
#
# AGENTS.md requires repository checks, not client hooks, to own enforcement.
# This check is read-only: it inspects git history and writes nothing, so an
# effectively read-only reviewer can run it.
set -euo pipefail
export GIT_NO_REPLACE_OBJECTS=1
export LC_ALL=C

cd "$(git rev-parse --show-toplevel)"

# Last commit written under the pre-marker convention. Commits at or before this
# SHA are historical and exempt. Advancing this baseline is a policy weakening
# and requires the same authority as any other gate change.
baseline="f19d2a6c941aeeebdb125f85a02ef5bd47198bed"

if ! git cat-file -e "${baseline}^{commit}" 2>/dev/null; then
  echo "commit message check unavailable: baseline ${baseline} not in this clone" >&2
  echo "fetch full history (for example actions/checkout with fetch-depth: 0)" >&2
  exit 1
fi

if [ "$(git rev-parse --is-shallow-repository)" != "false" ]; then
  echo "commit message check unavailable: complete history is required" >&2
  echo "fetch full history (for example actions/checkout with fetch-depth: 0)" >&2
  exit 1
fi

if ! git merge-base --is-ancestor "$baseline" HEAD; then
  echo "commit message check unavailable: baseline ${baseline} is not an ancestor of HEAD" >&2
  exit 1
fi

# area(marker): summary
#   area   - lowercase subsystem, matching the existing history
#   marker - planning | seed | a milestone slug (M0, v0.1, 1.0, kernel-a)
title_pattern='^[a-z][a-z0-9_-]*\(([A-Za-z0-9][A-Za-z0-9._-]*)\): [^[:space:]]([[:print:]]*[^[:space:]])?$'
milestone_m_pattern='^M[0-9]+$'
milestone_version_pattern='^v?[0-9]+(\.[0-9]+)+$'
milestone_slug_pattern='^[a-z0-9]+(-[a-z0-9]+)*$'
banned_pattern='co[ _-]*authored[ _-]+by|generated[ _-]+(by|with)|(authored|written|created|assisted|developed)[ _-]+(by|with)[[:space:]]+(chatgpt|claude|codex|gemini|copilot|an?[[:space:]]+ai|llm)|🤖'

# Return 0 for a banned match, 1 for a clean nonmatch, and 2 for any producer,
# normalization, or grep error. Callers must distinguish all three outcomes.
scan_attribution() {
  local body="$1"
  local pipeline_status

  printf '%s\n' "$body" | tr '[:space:]' ' ' | grep -iE "$banned_pattern" >/dev/null
  pipeline_status=("${PIPESTATUS[@]}")
  if [ "${pipeline_status[0]}" -ne 0 ] \
    || [ "${pipeline_status[1]}" -ne 0 ] \
    || [ "${pipeline_status[2]}" -gt 1 ]
  then
    return 2
  fi
  return "${pipeline_status[2]}"
}

valid_title() {
  local title="$1"
  local marker

  if [[ ! "$title" =~ $title_pattern ]]; then
    return 1
  fi
  marker="${BASH_REMATCH[1]}"

  if [ "${#marker}" -gt 64 ]; then
    return 1
  fi

  if [[ ! "$marker" =~ $milestone_m_pattern \
    && ! "$marker" =~ $milestone_version_pattern \
    && ! "$marker" =~ $milestone_slug_pattern ]]
  then
    return 1
  fi
  case "$marker" in
    readme|con|prn|aux|nul|com[1-9]|lpt[1-9]|*-gate|*-technical) return 1 ;;
  esac
}

# Prospective controls keep flexible operator slugs aligned with the documented
# path grammar instead of testing only names already present in history.
for title in \
  'repo(planning): control' \
  'repo(seed): control' \
  'repo(M0): control' \
  'repo(v0.1): control' \
  'repo(1.0): control' \
  'repo(kernel-a): control'
do
  if ! valid_title "$title"; then
    echo "commit message check misconfigured: valid prospective title rejected: $title" >&2
    exit 1
  fi
done
for title in \
  'Repo(kernel-a): control' \
  'repo(README): control' \
  'repo(readme): control' \
  'repo(kernel-gate): control' \
  'repo(kernel-technical): control' \
  'repo(kernel--a): control' \
  'repo(kernel_a): control' \
  'repo(kernel.a): control' \
  'repo(con): control' \
  'repo(lpt9): control' \
  'repo(aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa): control' \
  $'repo(kernel-a): \tcontrol' \
  $'repo(kernel-a): control\t' \
  'repo(-kernel): control'
do
  if valid_title "$title"; then
    echo "commit message check misconfigured: invalid prospective title accepted: $title" >&2
    exit 1
  fi
done

for body in \
  'Generated by Claude' \
  'AI-generated by Codex' \
  'Authored by ChatGPT' \
  'Written by Codex' \
  'Created by Claude' \
  'Assisted by ChatGPT' \
  'Developed with Claude' \
  $'Generated\tby Claude' \
  $'Generated\nby Claude' \
  $'Generated\vby Claude' \
  $'Generated\fby Claude' \
  'generated with an LLM'
do
  if scan_attribution "$body"; then
    continue
  else
    scan_status=$?
  fi
  if [ "$scan_status" -eq 1 ]; then
    echo "commit message check misconfigured: banned attribution accepted: $body" >&2
  else
    echo "commit message check unavailable: attribution control failed" >&2
  fi
  exit 1
done

status=0
range="${baseline}..HEAD"

if ! commits="$(git rev-list "$range")"; then
  echo "commit message check unavailable: could not enumerate ${range}" >&2
  exit 1
fi

expected=0
for _ in $commits; do
  expected=$((expected + 1))
done
seen=0

# One `git log` for the whole range instead of two per commit. Every git call is
# a process spawn, and under a restricted sandbox each one also emits a platform
# warning, so a per-commit loop buries the real output a reviewer needs to read.
# Records are NUL-separated and fields use unit separator. The stream is read
# directly rather than captured, because command substitution cannot carry NUL.
while IFS= read -r -d '' record; do
  seen=$((seen + 1))
  sha="${record%%$'\x1f'*}"
  rest="${record#*$'\x1f'}"
  title="${rest%%$'\x1f'*}"
  body="${rest#*$'\x1f'}"

  if ! valid_title "$title"; then
    echo "$sha: title must be 'area(marker): summary' with marker planning, seed, or a milestone" >&2
    echo "  got: $title" >&2
    status=1
  fi

  if [ "${#title}" -gt 72 ]; then
    echo "$sha: title is ${#title} characters; keep it at 72 or fewer" >&2
    status=1
  fi

  if scan_attribution "$body"; then
    echo "$sha: no content-origin attribution or generated-by claims in commit messages" >&2
    status=1
  else
    scan_status=$?
    if [ "$scan_status" -ne 1 ]; then
      echo "$sha: attribution scan unavailable" >&2
      status=1
    fi
  fi
done < <(git log -z --format="%H%x1f%s%x1f%B" "$range")

# A short stream means the log call failed or was truncated. Fail closed rather
# than silently checking fewer commits than the range contains.
if [ "$seen" -ne "$expected" ]; then
  echo "commit message check unavailable: read ${seen} of ${expected} commits in ${range}" >&2
  exit 1
fi

if [ "$status" -ne 0 ]; then
  exit 1
fi

# Always report the fixed policy baseline so the checked range remains visible
# in retained evidence. Changing this byte is a gate-policy change.
echo "commit message check passed (baseline ${baseline})"
